	class vn_m1897;
	class vn_m1897_bcsewpn:  vn_m1897{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m1897_bayo;
	class vn_m1897_bayo_bcsewpn:  vn_m1897_bayo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_izh54;
	class vn_izh54_bcsewpn:  vn_izh54{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_izh54_shorty;
	class vn_izh54_shorty_bcsewpn:  vn_izh54_shorty{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_izh54_p;
	class vn_izh54_p_bcsewpn:  vn_izh54_p{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_mp40;
	class vn_mp40_bcsewpn:  vn_mp40{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_mat49;
	class vn_mat49_bcsewpn:  vn_mat49{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_mat49_f;
	class vn_mat49_f_bcsewpn:  vn_mat49_f{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_mat49_sd;
	class vn_mat49_sd_bcsewpn:  vn_mat49_sd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_mat49_vc;
	class vn_mat49_vc_bcsewpn:  vn_mat49_vc{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_ppsh41;
	class vn_ppsh41_bcsewpn:  vn_ppsh41{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_k50m;
	class vn_k50m_bcsewpn:  vn_k50m{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m3a1;
	class vn_m3a1_bcsewpn:  vn_m3a1{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m3sd;
	class vn_m3sd_bcsewpn:  vn_m3sd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_sten;
	class vn_sten_bcsewpn:  vn_sten{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_sten_sd;
	class vn_sten_sd_bcsewpn:  vn_sten_sd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_mc10;
	class vn_mc10_bcsewpn:  vn_mc10{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_mc10_sd;
	class vn_mc10_sd_bcsewpn:  vn_mc10_sd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m45;
	class vn_m45_bcsewpn:  vn_m45{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m45_fold;
	class vn_m45_fold_bcsewpn:  vn_m45_fold{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m45_camo;
	class vn_m45_camo_bcsewpn:  vn_m45_camo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo1"};
		hiddenSelectionsTextures[] = {"","\vn\weapons_f_vietnam\m45\data\vn_m45_01_camo_co.paa"};
	};
	class vn_m45_sd;
	class vn_m45_sd_bcsewpn:  vn_m45_sd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_type56;
	class vn_type56_bcsewpn:  vn_type56{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_type56_bayo;
	class vn_type56_bayo_bcsewpn:  vn_type56_bayo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m1carbine;
	class vn_m1carbine_bcsewpn:  vn_m1carbine{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m2carbine;
	class vn_m2carbine_bcsewpn:  vn_m2carbine{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m3carbine;
	class vn_m3carbine_bcsewpn:  vn_m3carbine{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m1carbine_gl;
	class vn_m1carbine_gl_bcsewpn:  vn_m1carbine_gl{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m2carbine_gl;
	class vn_m2carbine_gl_bcsewpn:  vn_m2carbine_gl{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m1carbine_sniper;
	class vn_m1carbine_sniper_bcsewpn:  vn_m1carbine_sniper{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m2carbine_sniper;
	class vn_m2carbine_sniper_bcsewpn:  vn_m2carbine_sniper{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m1carbine_bayo;
	class vn_m1carbine_bayo_bcsewpn:  vn_m1carbine_bayo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m2carbine_bayo;
	class vn_m2carbine_bayo_bcsewpn:  vn_m2carbine_bayo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m16;
	class vn_m16_bcsewpn:  vn_m16{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m16_camo;
	class vn_m16_camo_bcsewpn:  vn_m16_camo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo1"};
		hiddenSelectionsTextures[] = {"","\vn\weapons_f_vietnam\m16a1\data\vn_m16_01_g_co.paa"};
	};
	class vn_m16_bayo;
	class vn_m16_bayo_bcsewpn:  vn_m16_bayo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m16_sd;
	class vn_m16_sd_bcsewpn:  vn_m16_sd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m16_mrk;
	class vn_m16_mrk_bcsewpn:  vn_m16_mrk{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m16_mrk_sd;
	class vn_m16_mrk_sd_bcsewpn:  vn_m16_mrk_sd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m16_sniper;
	class vn_m16_sniper_bcsewpn:  vn_m16_sniper{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m16_sniper_sd;
	class vn_m16_sniper_sd_bcsewpn:  vn_m16_sniper_sd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m16_nvg;
	class vn_m16_nvg_bcsewpn:  vn_m16_nvg{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m16_nvg_sd;
	class vn_m16_nvg_sd_bcsewpn:  vn_m16_nvg_sd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m16_xm148;
	class vn_m16_xm148_bcsewpn:  vn_m16_xm148{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_xm177;
	class vn_xm177_bcsewpn:  vn_xm177{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_xm177_camo;
	class vn_xm177_camo_bcsewpn:  vn_xm177_camo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo1"};
		hiddenSelectionsTextures[] = {"","\vn\weapons_f_vietnam\xm177\data\vn_xm177_01_camo_co.paa"};
	};
	class vn_xm177_mrk;
	class vn_xm177_mrk_bcsewpn:  vn_xm177_mrk{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_xm177_sniper;
	class vn_xm177_sniper_bcsewpn:  vn_xm177_sniper{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_xm177_nvg;
	class vn_xm177_nvg_bcsewpn:  vn_xm177_nvg{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_xm177_xm148;
	class vn_xm177_xm148_bcsewpn:  vn_xm177_xm148{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_xm177_fg;
	class vn_xm177_fg_bcsewpn:  vn_xm177_fg{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_xm177_short;
	class vn_xm177_short_bcsewpn:  vn_xm177_short{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_xm177_stock;
	class vn_xm177_stock_bcsewpn:  vn_xm177_stock{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m63a;
	class vn_m63a_bcsewpn:  vn_m63a{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m63a_cdo;
	class vn_m63a_cdo_bcsewpn:  vn_m63a_cdo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo1","cam02"};
		hiddenSelectionsTextures[] = {"","\vn\weapons_f_vietnam_02\m63a\data\vn_m63a_cdo_01_co.paa","\vn\weapons_f_vietnam_02\m63a\data\vn_m63a_cdo_01_ca.paa"};
	};
	class vn_m63a_lmg;
	class vn_m63a_lmg_bcsewpn:  vn_m63a_lmg{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo1","cam02"};
		hiddenSelectionsTextures[] = {"","\vn\weapons_f_vietnam_02\m63a\data\vn_m63a_lmg_01_co.paa","\vn\weapons_f_vietnam_02\m63a\data\vn_m63a_cdo_01_co.paa"};
	};
	class vn_m14;
	class vn_m14_bcsewpn:  vn_m14{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m14_camo;
	class vn_m14_camo_bcsewpn:  vn_m14_camo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo1"};
		hiddenSelectionsTextures[] = {"","\vn\weapons_f_vietnam\m14\data\vn_m14_02_co.paa"};
	};
	class vn_m14_sd;
	class vn_m14_sd_bcsewpn:  vn_m14_sd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m14_bayo;
	class vn_m14_bayo_bcsewpn:  vn_m14_bayo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m21;
	class vn_m21_bcsewpn:  vn_m21{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m21_sd;
	class vn_m21_sd_bcsewpn:  vn_m21_sd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m21_nvg;
	class vn_m21_nvg_bcsewpn:  vn_m21_nvg{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m21_nvg_sd;
	class vn_m21_nvg_sd_bcsewpn:  vn_m21_nvg_sd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m40a1;
	class vn_m40a1_bcsewpn:  vn_m40a1{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m40a1_sniper;
	class vn_m40a1_sniper_bcsewpn:  vn_m40a1_sniper{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m40a1_sniper_sd;
	class vn_m40a1_sniper_sd_bcsewpn:  vn_m40a1_sniper_sd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo1"};
		hiddenSelectionsTextures[] = {"","\vn\weapons_f_vietnam\m40a1\data\vn_m40a1_02_co.paa"};
	};
	class vn_m40a1_nvg;
	class vn_m40a1_nvg_bcsewpn:  vn_m40a1_nvg{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m40a1_nvg_sd;
	class vn_m40a1_nvg_sd_bcsewpn:  vn_m40a1_nvg_sd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo1"};
		hiddenSelectionsTextures[] = {"","\vn\weapons_f_vietnam\m40a1\data\vn_m40a1_02_co.paa"};
	};
	class vn_m4956;
	class vn_m4956_bcsewpn:  vn_m4956{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m4956_bayo;
	class vn_m4956_bayo_bcsewpn:  vn_m4956_bayo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m4956_sniper;
	class vn_m4956_sniper_bcsewpn:  vn_m4956_sniper{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m4956_gl;
	class vn_m4956_gl_bcsewpn:  vn_m4956_gl{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m38;
	class vn_m38_bcsewpn:  vn_m38{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m38_bayo;
	class vn_m38_bayo_bcsewpn:  vn_m38_bayo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m1891;
	class vn_m1891_bcsewpn:  vn_m1891{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m1891_bayo;
	class vn_m1891_bayo_bcsewpn:  vn_m1891_bayo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m9130;
	class vn_m9130_bcsewpn:  vn_m9130{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m9130_bayo;
	class vn_m9130_bayo_bcsewpn:  vn_m9130_bayo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m9130_sniper;
	class vn_m9130_sniper_bcsewpn:  vn_m9130_sniper{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_sks;
	class vn_sks_bcsewpn:  vn_sks{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_sks_bayo;
	class vn_sks_bayo_bcsewpn:  vn_sks_bayo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_sks_gl;
	class vn_sks_gl_bcsewpn:  vn_sks_gl{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_rpd;
	class vn_rpd_bcsewpn:  vn_rpd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_rpd_shorty;
	class vn_rpd_shorty_bcsewpn:  vn_rpd_shorty{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_pk;
	class vn_pk_bcsewpn:  vn_pk{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m60;
	class vn_m60_bcsewpn:  vn_m60{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m60_shorty;
	class vn_m60_shorty_bcsewpn:  vn_m60_shorty{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";

		hiddenSelections[] = {"zasleh","camo1","camo2"};
		hiddenSelectionsTextures[] = {"","\vn\weapons_f_vietnam\m60\data\vn_m60_01_camo_co.paa","\vn\weapons_f_vietnam\m60\data\vn_m60_02_co.paa"};
	};
	class vn_m60_shorty_camo;
	class vn_m60_shorty_camo_bcsewpn:  vn_m60_shorty_camo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo1","camo2"};
		hiddenSelectionsTextures[] = {"","\vn\weapons_f_vietnam\m60\data\vn_m60_01_camo_co.paa","\vn\weapons_f_vietnam\m60\data\vn_m60_02_co.paa"};
	};

	class vn_m79;
	class vn_m79_bcsewpn:  vn_m79{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_m10_sd;
	class vn_m10_sd_bcsewpn:  vn_m10_sd{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_pps52;
	class vn_pps52_bcsewpn:  vn_pps52{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_pps43;
	class vn_pps43_bcsewpn:  vn_pps43{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_xm177_xm148_camo;
	class vn_xm177_xm148_camo_bcsewpn:  vn_xm177_xm148_camo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo1","camo2"};
		hiddenSelectionsTextures[] = {"","\vn\weapons_f_vietnam\xm177\data\vn_xm177_01_camo_co.paa","\vn\weapons_f_vietnam\xm177\data\vn_xm148_01_camo_co.paa"};
	};
	class vn_xm177_stock_camo;
	class vn_xm177_stock_camo_bcsewpn:  vn_xm177_stock_camo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo1","camo2"};
		hiddenSelectionsTextures[] = {"","\vn\weapons_f_vietnam\xm177\data\vn_xm177_01_camo_co.paa","\vn\weapons_f_vietnam\m16a1\data\vn_m16_01_g_co.paa"};
	};

	class vn_m40a1_camo;
	class vn_m40a1_camo_bcsewpn:  vn_m40a1_camo{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh","camo1"};
		hiddenSelectionsTextures[] = {"","\vn\weapons_f_vietnam\m40a1\data\vn_m40a1_02_co.paa"};
	};
	class vn_sks_sniper;
	class vn_sks_sniper_bcsewpn:  vn_sks_sniper{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};

	class vn_rpd_shorty_01;
	class vn_rpd_shorty_01_bcsewpn:  vn_rpd_shorty_01{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
	class vn_dp28;
	class vn_dp28_bcsewpn:  vn_dp28{
		enableAttack = 0;
		type = 4;
		scope = 1;
		scopeArsenal = 0;
		handAnim[] = {};
		modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
		muzzles[] = {"this","NGL"};
		class NGL: NGL{};
		_generalMacro = "";
		baseWeapon = "";
		hiddenSelections[] = {"zasleh"};
		hiddenSelectionsTextures[] = {""};
	};
		class vn_s_mpu;
	class vn_s_mpu_bcsewpn:  vn_s_mpu
	{
	enableAttack = 0;
	type = 4;
	scope = 1;
	scopeArsenal = 0;
	handAnim[] = {};
	modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
	muzzles[] = {"this","NGL"};
	class NGL: NGL{};
	_generalMacro = "";
	baseWeapon = "";
	hiddenSelections[] = {"zasleh"};
	hiddenSelectionsTextures[] = {""};
	};
	class vn_mk1_udg;
	class vn_mk1_udg_bcsewpn:  vn_mk1_udg
	{
	enableAttack = 0;
	type = 4;
	scope = 1;
	scopeArsenal = 0;
	handAnim[] = {};
	modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
	muzzles[] = {"this","NGL"};
	class NGL: NGL{};
	_generalMacro = "";
	baseWeapon = "";
	hiddenSelections[] = {"zasleh"};
	hiddenSelectionsTextures[] = {""};
	};
	class vn_mpu;
	class vn_mpu_bcsewpn:  vn_mpu
	{
	enableAttack = 0;
	type = 4;
	scope = 1;
	scopeArsenal = 0;
	handAnim[] = {};
	modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
	muzzles[] = {"this","NGL"};
	class NGL: NGL{};
	_generalMacro = "";
	baseWeapon = "";
	hiddenSelections[] = {"zasleh"};
	hiddenSelectionsTextures[] = {""};
	};
	class vn_mpu_sd;
	class vn_mpu_sd_bcsewpn:  vn_mpu_sd
	{
	enableAttack = 0;
	type = 4;
	scope = 1;
	scopeArsenal = 0;
	handAnim[] = {};
	modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
	muzzles[] = {"this","NGL"};
	class NGL: NGL{};
	_generalMacro = "";
	baseWeapon = "";
	hiddenSelections[] = {"zasleh"};
	hiddenSelectionsTextures[] = {""};
	};
	class vn_vz61;
	class vn_vz61_bcsewpn:  vn_vz61
	{
	enableAttack = 0;
	type = 4;
	scope = 1;
	scopeArsenal = 0;
	handAnim[] = {};
	modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
	muzzles[] = {"this","NGL"};
	class NGL: NGL{};
	_generalMacro = "";
	baseWeapon = "";
	hiddenSelections[] = {"zasleh"};
	hiddenSelectionsTextures[] = {""};
	};
	class vn_m1a1_tommy;
	class vn_m1a1_tommy_bcsewpn:  vn_m1a1_tommy
	{
	enableAttack = 0;
	type = 4;
	scope = 1;
	scopeArsenal = 0;
	handAnim[] = {};
	modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
	muzzles[] = {"this","NGL"};
	class NGL: NGL{};
	_generalMacro = "";
	baseWeapon = "";
	hiddenSelections[] = {"zasleh"};
	hiddenSelectionsTextures[] = {""};
	};
	class vn_m1a1_tommy_so;
	class vn_m1a1_tommy_so_bcsewpn:  vn_m1a1_tommy_so
	{
	enableAttack = 0;
	type = 4;
	scope = 1;
	scopeArsenal = 0;
	handAnim[] = {};
	modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
	muzzles[] = {"this","NGL"};
	class NGL: NGL{};
	_generalMacro = "";
	baseWeapon = "";
	hiddenSelections[] = {"zasleh"};
	hiddenSelectionsTextures[] = {""};
	};
	class vn_m1928a1_tommy;
	class vn_m1928a1_tommy_bcsewpn:  vn_m1928a1_tommy
	{
	enableAttack = 0;
	type = 4;
	scope = 1;
	scopeArsenal = 0;
	handAnim[] = {};
	modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
	muzzles[] = {"this","NGL"};
	class NGL: NGL{};
	_generalMacro = "";
	baseWeapon = "";
	hiddenSelections[] = {"zasleh"};
	hiddenSelectionsTextures[] = {""};
	};
	class vn_m1928_tommy;
	class vn_m1928_tommy_bcsewpn:  vn_m1928_tommy
	{
	enableAttack = 0;
	type = 4;
	scope = 1;
	scopeArsenal = 0;
	handAnim[] = {};
	modes[] = {"Noob_Auto"};
		class Noob_Auto:Noob_Auto{};
	muzzles[] = {"this","NGL"};
	class NGL: NGL{};
	_generalMacro = "";
	baseWeapon = "";
	hiddenSelections[] = {"zasleh"};
	hiddenSelectionsTextures[] = {""};
	};

